###

GET http://localhost:3000/posts

###

GET http://localhost:3000/posts?owner=linophir

###

GET http://localhost:3000/posts/6734b0c818a1cf8344804554

###

POST http://localhost:3000/posts
Content-Type: application/json

{
    "title": "Hello",
    "owner": "linophir",
    "content": "Hello World..."
}

###

DELETE http://localhost:3000/posts/6734b0c818a1cf8344804554

###

GET http://localhost:3000/posts?sender=linophir 

###

PUT http://localhost:3000/posts/6734b0c818a1cf8344804554
Content-Type: application/json

{
    "title": "Updated Title",
    "content": "This is the updated content of the post."
}


### 
POST /comments
Content-Type: application/json
Body:
{
  "postId": "ObjectId",
  "author": "string",
  "content": "string"
}

### 
GET /comments/post/{postId}
Response:
[
  {
    "postId": "ObjectId",
    "author": "string",
    "content": "string",
    "createdAt": "timestamp"
  }
]

### 
PUT /comments/{id}
Content-Type: application/json
Body:
{
  "content": "updated content"
}

### 
DELETE /comments/{id}
Response:
{
  "message": "Comment deleted successfully"
}
